### ISSUE TITLE
Prebuilt firmware does not fit in a Digispark ATtiny85

### ISSUE THREAD

**Issue by Cyberwizzard** [micronucleus/micronucleus#22]
I downloaded from github, compiled the 'micronucleus' program and tried uploading the prebuilt firmware. I tried versions 1.05 and 1.06, but both give an error stating that the program is roughly 2100 bytes too big for the Digispark.

What to do?

**Comment by w-A-L-L-e** [comment]
Do you have an example of bootloader_data.c?
I want to upload a firmware with less delay (2 second version instead of the 5sec) but also bumped into that error when trying to flash a .hex file with micronucleus:
walterschreppers@Walters-MBP:~/cppWork/AVR_CHIPS/DigiStampAttiny85/micronucleus_latest/firmware/releases$ ls
Nanite841.hex       t167_default.hex    t45_default.hex     t841_default.hex    t84_default.hex     t85_aggressive.hex  t85_default.hex
walterschreppers@Walters-MBP:~/cppWork/AVR_CHIPS/DigiStampAttiny85/micronucleus_latest/firmware/releases$ /Users/walterschreppers/Library/Arduino15/packages/digistump/tools/micronucleus/2.0a4/micronucleus t85_aggressive.hex 
> Please plug in the device ... 
> Press CTRL+C to terminate the program.
> Device is found!
connecting: 40% complete
> Device has firmware version 1.6
> Available space for user applications: 6012 bytes
> Suggested sleep time between sending pages: 8ms
> Whole page count: 94  page size: 64
> Erase function sleep duration: 752ms
parsing: 60% complete
> Program file is 2130 bytes too big for the bootloader!

When I look in upgrade.c I see  #include "./bootloader_data.c" -> but this is not available in the micronucleus repo nor do I know what to put in it? 
Guessing something like char const bootloader_data="....???

**Comment by w-A-L-L-e** [comment]
@Cyberwizzard what upgrade folder? there is only upgrade.c here?

**Comment by w-A-L-L-e** [comment]
Ok nevermind my previous comments. In version 1.11 all is clear and there is an example + the generate_data.rb. In latest micronucleus however this dir + explanation is omitted ;). Upgrading worked for me now. Thanks all...

**Comment by senolcalisan** [comment]
@w-a-l-l-e 
Could you explain briefly for upgrading attiny micronucleus bootloader.
